# Generated by Django 5.1.4 on 2026-05-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('scholarship', '장학'), ('academic', '학사'), ('event', '행사'), ('exam', '시험'), ('general', '일반')], max_length=20, verbose_name='태그')),
                ('tone', models.CharField(choices=[('neutral', 'Neutral'), ('blue', 'Blue'), ('sky', 'Sky'), ('purple', 'Purple'), ('gold', 'Gold'), ('success', 'Success'), ('warn', 'Warn')], default='neutral', max_length=10, verbose_name='색상')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('summary', models.TextField(verbose_name='요약')),
                ('content', models.TextField(blank=True, verbose_name='본문')),
                ('source_url', models.URLField(blank=True, verbose_name='원문 URL')),
                ('published_at', models.DateField(verbose_name='게시일')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='만료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항 목록',
                'ordering': ['-published_at'],
            },
        ),
    ]
