# Generated by Django 5.1.4 on 2026-05-11 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='건물명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='건물코드')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('map_x', models.FloatField(default=0, verbose_name='지도 X')),
                ('map_y', models.FloatField(default=0, verbose_name='지도 Y')),
                ('map_w', models.FloatField(default=60, verbose_name='지도 너비')),
                ('map_h', models.FloatField(default=40, verbose_name='지도 높이')),
                ('floors', models.PositiveSmallIntegerField(default=5, verbose_name='층수')),
                ('has_elevator', models.BooleanField(default=True, verbose_name='엘리베이터')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '건물',
                'verbose_name_plural': '건물 목록',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='노드명')),
                ('node_type', models.CharField(choices=[('entrance', '건물 입구'), ('junction', '교차점'), ('stairs', '계단'), ('elevator', '엘리베이터'), ('slope', '경사로')], max_length=20, verbose_name='노드 유형')),
                ('map_x', models.FloatField(verbose_name='지도 X')),
                ('map_y', models.FloatField(verbose_name='지도 Y')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='campus.building')),
            ],
            options={
                'verbose_name': '경로 노드',
                'verbose_name_plural': '경로 노드 목록',
            },
        ),
        migrations.CreateModel(
            name='RouteEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_m', models.FloatField(verbose_name='거리(m)')),
                ('stair_count', models.IntegerField(default=0, verbose_name='계단 수')),
                ('slope_pct', models.FloatField(default=0, verbose_name='경사도(%)')),
                ('has_elevator', models.BooleanField(default=False, verbose_name='엘리베이터')),
                ('is_indoor', models.BooleanField(default=False, verbose_name='실내')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='campus.routenode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='campus.routenode')),
            ],
            options={
                'verbose_name': '경로 엣지',
                'verbose_name_plural': '경로 엣지 목록',
                'unique_together': {('source', 'target')},
            },
        ),
    ]
