# Generated by Django 5.1.4 on 2026-05-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('course', models.CharField(blank=True, max_length=100, verbose_name='관련 강의')),
                ('tags', models.JSONField(default=list, verbose_name='태그')),
                ('is_weak', models.BooleanField(default=False, verbose_name='이해 부족')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '메모',
                'verbose_name_plural': '메모 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, verbose_name='연결 강도')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '메모 연결',
                'verbose_name_plural': '메모 연결 목록',
            },
        ),
    ]
