# Generated by Django 5.1.4 on 2026-05-11 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='강의명')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='강의코드')),
                ('professor', models.CharField(max_length=50, verbose_name='교수명')),
                ('room', models.CharField(max_length=50, verbose_name='강의실')),
                ('department', models.CharField(max_length=100, verbose_name='개설학과')),
                ('course_type', models.CharField(choices=[('major_req', '전공필수'), ('major_elec', '전공선택'), ('gen_req', '교양필수'), ('gen_elec', '교양선택')], max_length=20, verbose_name='이수구분')),
                ('credits', models.PositiveSmallIntegerField(default=3, verbose_name='학점')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, '월'), (1, '화'), (2, '수'), (3, '목'), (4, '금')], verbose_name='요일')),
                ('start_hour', models.FloatField(verbose_name='시작시간')),
                ('duration', models.FloatField(default=1.25, verbose_name='수업시간(h)')),
                ('tone', models.CharField(choices=[('blue', 'Blue'), ('sky', 'Sky'), ('purple', 'Purple'), ('gold', 'Gold')], default='blue', max_length=10, verbose_name='색상')),
                ('semester', models.CharField(max_length=10, verbose_name='학기')),
            ],
            options={
                'verbose_name': '강의',
                'verbose_name_plural': '강의 목록',
                'ordering': ['day', 'start_hour'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course')),
            ],
            options={
                'verbose_name': '수강신청',
                'verbose_name_plural': '수강신청 목록',
            },
        ),
    ]
