# Generated by Django 5.1.4 on 2026-05-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_meeting_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('major_req', '전공필수'), ('major_elec', '전공선택'), ('major_undiv', '전공'), ('general', '교양')], max_length=20, verbose_name='이수구분'),
        ),
    ]
