# Generated by Django 5.1.4 on 2026-05-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverification_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('medicine', '의학과'), ('nursing', '간호학과'), ('medical_lab', '임상병리학과'), ('physical_therapy', '물리치료학과'), ('occupational_therapy', '작업치료학과'), ('radiology', '방사선학과'), ('health_admin', '보건행정경영학과'), ('korean_lang', '국어국문학과'), ('english_lang', '영어영문학과'), ('history', '사학과'), ('philosophy', '철학과'), ('social_welfare', '사회복지학과'), ('law', '법학과'), ('public_admin', '행정학과'), ('economics', '경제학과'), ('business', '경영학과'), ('accounting', '회계학과'), ('trade', '무역학과'), ('math', '수학과'), ('physics', '물리학과'), ('chemistry', '화학과'), ('biology', '생명과학과'), ('food_nutrition', '식품영양학과'), ('child_family', '아동가족학과'), ('mechanical_eng', '기계공학과'), ('electrical_eng', '전기공학과'), ('electronic_eng', '전자공학과'), ('chemical_eng', '화학공학과'), ('civil_eng', '토목환경공학과'), ('architecture', '건축학과'), ('industrial_eng', '산업경영공학과'), ('computer_sw', '컴퓨터소프트웨어공학과'), ('ai_bigdata', 'AI빅데이터학과'), ('information_security', '정보보호학과'), ('media_comm', '미디어커뮤니케이션학과'), ('game', '게임학과'), ('design', '디자인학과'), ('sports', '스포츠과학과')], max_length=50, verbose_name='전공'),
        ),
    ]
